version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    networks:
      - spda_network
    command: bash -c "
      /wait_for_it.sh $DB_HOST:$DB_PORT &&
      sleep 1 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - ./.env
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - spda_pg_data:/var/lib/postgresql/data
    hostname: db
    networks:
      - spda_network
    env_file:
      - ./.env

networks:
  spda_network:

volumes:
  spda_pg_data:
